language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-filter-mermaid-diagrams


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "xiaoxian"
  - git config user.email "self@yu-xiaoxian.me"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/Yu-Xiaoxian/Yu-Xiaoxian.github.io.git